name: build CI

on:
    push:
        branches: main
    workflow_dispatch:
    workflow_call:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest,ubuntu-22.04]
        runs-on: ${{matrix.os}}
        steps:
        - uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.8
            cache: 'pip' 
            cache-dependency-path: '**/requirements.txt'
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Build
          run: |
            pip install pyinstaller
            pyinstaller -F patcher.py
        - name: Upload
          uses: actions/upload-artifact@v4
          with: 
            name: build-${{matrix.os}}
            path: ./dist
